ITDoorsOperBundle_department:
        resource: "@ITDoorsOperBundle/Resources/config/routing/department.yml"
        prefix:   /department
        
ITDoorsOperBundle_city:
        resource: "@ITDoorsOperBundle/Resources/config/routing/city.yml"
        prefix:   /city

ITDoorsOperBundle_organization:
        resource: "@ITDoorsOperBundle/Resources/config/routing/organization.yml"
        prefix:   /organization