parameters:
#    it_doors_oper.example.class: ITDoors\OperBundle\Example

services:
#    it_doors_oper.example:
#        class: %it_doors_oper.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
